name: Convert TXT to YAML
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  process-rename-and-push:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 处理文件并重命名
      - name: Process and rename files
        run: |
          process_file() {
            input_file="$1"
            output_file="$2"
            tmp_file=$(mktemp)

            # 首先处理注释和规则，将 payload: 插入到正确的位置
            payload_inserted=false
            while IFS= read -r line; do
              if [[ $line == \#* ]] || [[ -z $line ]]; then
                echo "$line" >> "$tmp_file"
              else
                if ! $payload_inserted; then
                  echo "payload:" >> "$tmp_file"
                  payload_inserted=true
                fi
                echo "  - $line" >> "$tmp_file"
              fi
            done < "$input_file"

            mv "$tmp_file" "$output_file"
          }

          # 处理并重命名文件
          process_file "adblock_reject_shadowrocket_ruleset.txt" "adblock_reject_shadowrocket_ruleset.yaml"

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add adblock_reject_shadowrocket_ruleset.yaml
          git commit -m "Convert TXT to YAML" || exit 0

          # 拉取远程仓库的最新更改并合并
          git pull --rebase

          # 推送错误重试机制
          max_retries=5
          retry_count=0

          until [ $retry_count -ge $max_retries ]
          do
            git push && break
            retry_count=$((retry_count + 1))
            echo "Push failed. Retry $retry_count/$max_retries in 30 seconds..."
            sleep 30
          done

          if [ $retry_count -ge $max_retries ]; then
            echo "Failed to push changes after $max_retries attempts"
            exit 1
          fi
