name: Process and Rename TXT to YAML
on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  process-rename-and-push:
    runs-on: ubuntu-latest
    steps:
      # 检出仓库
      - name: Checkout repository
        uses: actions/checkout@v2

      # 处理文件并重命名
      - name: Process and rename files
        run: |
          process_file() {
            input_file="$1"
            output_file="$2"
            echo "payload:" > "$output_file"
            while IFS= read -r line; do
              if [[ $line == \#* ]] || [[ -z $line ]]; then
                echo "  $line" >> "$output_file"
              else
                echo "  - $line" >> "$output_file"
              fi
            done < "$input_file"
          }

          process_file "adblock_reject_surge_ruleset.txt" "adblock_reject_surge_ruleset.yaml"
          process_file "adblock_reject_surge_domainset.txt" "adblock_reject_surge_domainset.yaml"

      # 提交并推送更改
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add adblock_reject_surge_ruleset.yaml adblock_reject_surge_domainset.yaml
          git commit -m "Process and rename TXT to YAML" || exit 0
          
          # 推送错误重试机制
          max_retries=5
          retry_count=0
          
          while [ $retry_count -lt $max_retries ]; do
            if git push; then
              echo "Successfully pushed changes"
              exit 0
            else
              echo "Push failed. Retrying in 30 seconds..."
              sleep 30
              retry_count=$((retry_count + 1))
            fi
          done
          
          echo "Failed to push changes after $max_retries attempts"
          exit 1
        env:
          TOKEN: ${{ secrets.TOKEN }}
