name: Release_ADblock_file

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟运行一次
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current time
        id: current-time
        run: echo "time=$(date +'%y%m%d%H%M')" >> $GITHUB_ENV

      - name: Update timestamp file
        run: echo "${{ env.time }}" > timestamp.txt

      - name: Force add and commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f timestamp.txt
          git commit -m "Forced update of timestamp" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin main --force
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse -q --verify "refs/tags/release-${{ env.time }}"; then
            echo "Tag exists."
            git tag -d release-${{ env.time }}
            git push origin :refs/tags/release-${{ env.time }}
          else
            echo "Tag does not exist."
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: release-${{ env.time }}
          release_name: Release ${{ env.time }}
          body: "Periodic release of adblock files."
          draft: false

      - name: Upload adblock_reject_surge_ruleset.list
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_surge_ruleset.list
          asset_name: adblock_reject_surge_ruleset.list
          asset_content_type: text/plain

      - name: Upload adblock_reject_surge_domainset.list
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./adblock_reject_surge_domainset.list
          asset_name: adblock_reject_surge_domainset.list
          asset_content_type: text/plain
