name: Trigger in sequence

on:
  workflow_dispatch:  # 允许手动触发工作流
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟自动触发一次

jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger and verify workflows
        env:
          TOKEN: ${{ secrets.TOKEN }}  # 使用GitHub secrets中存储的token
        run: |
          workflows=(
            "Run_AdBlock_Rule_Generator_RULESET.yml"
            "Run_AdBlock_Rule_Generator_DOMAINSET.yml"
            "Convert TXT to CONF.yml"
            "Convert TXT to LIST.yml"
            "Convert TXT to YAML.yml"
            "Release_ADblock_file.yml"
          )
          
          ref="main"
          
          for workflow_id in "${workflows[@]}"; do
            echo "Triggering workflow: $workflow_id"
            
            # 使用GitHub API触发工作流
            response=$(curl -X POST -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/workflows/$workflow_id/dispatches" \
              -d "{\"ref\":\"$ref\"}")
            echo "Triggered workflow $workflow_id: $response"

            # 循环检查工作流是否开始运行
            while : ; do
              status=$(curl -s -H "Authorization: token $TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?status=in_progress&branch=$ref" \
                | jq -r '.workflow_runs[0].status')

              if [[ "$status" == "in_progress" ]]; then
                echo "Workflow $workflow_id is running."
                break
              else
                echo "Waiting for workflow $workflow_id to start..."
                sleep 30
              fi
            done

            # 等待工作流完成
            while : ; do
              status=$(curl -s -H "Authorization: token $TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?status=completed&branch=$ref" \
                | jq -r '.workflow_runs[0].status')

              if [[ "$status" == "completed" ]]; then
                echo "Workflow $workflow_id has completed."
                break
              else
                echo "Waiting for workflow $workflow_id to complete..."
                sleep 60
              fi
            done

            # 检查工作流是否成功完成
            conclusion=$(curl -s -H "Authorization: token $TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/REIJI007/AdBlock_Rule_For_Surge/actions/runs?status=completed&branch=$ref" \
              | jq -r '.workflow_runs[0].conclusion')

            if [[ "$conclusion" != "success" ]]; then
              echo "Workflow $workflow_id failed or was cancelled. Stopping sequence."
              exit 1
            fi

            echo "Workflow $workflow_id completed successfully."
          done

          echo "All workflows completed successfully"
